# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regex',
        ),
    ]
